/*
 * Cashfree Payout APIs
 * Cashfree's Payout APIs provide developers with a streamlined pathway to integrate advanced payout capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2024-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cashfree.model;

import java.util.Objects;
import com.cashfree.model.CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.cashfree.JSON;

/**
 * It displays the details of the beneficiary.
 */
@Schema(description = "It displays the details of the beneficiary.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-11T10:35:59.070604Z[Etc/UTC]")
public class CreateTransferResponseBeneficiaryDetails {
  public static final String SERIALIZED_NAME_BENEFICIARY_ID = "beneficiary_id";
  @SerializedName(SERIALIZED_NAME_BENEFICIARY_ID)
  private String beneficiaryId;

  public static final String SERIALIZED_NAME_BENEFICIARY_INSTRUMENT_DETAILS = "beneficiary_instrument_details";
  @SerializedName(SERIALIZED_NAME_BENEFICIARY_INSTRUMENT_DETAILS)
  private CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails beneficiaryInstrumentDetails;

  public CreateTransferResponseBeneficiaryDetails() {
  }

  public CreateTransferResponseBeneficiaryDetails beneficiaryId(String beneficiaryId) {
    
    this.beneficiaryId = beneficiaryId;
    return this;
  }

   /**
   * It displays the unique ID to identify the beneficiary to whom you initiated the transfer request.
   * @return beneficiaryId
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "It displays the unique ID to identify the beneficiary to whom you initiated the transfer request.")
  public String getBeneficiaryId() {
    return beneficiaryId;
  }


  public void setBeneficiaryId(String beneficiaryId) {
    this.beneficiaryId = beneficiaryId;
  }


  public CreateTransferResponseBeneficiaryDetails beneficiaryInstrumentDetails(CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails beneficiaryInstrumentDetails) {
    
    this.beneficiaryInstrumentDetails = beneficiaryInstrumentDetails;
    return this;
  }

   /**
   * Get beneficiaryInstrumentDetails
   * @return beneficiaryInstrumentDetails
  **/
  @javax.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails getBeneficiaryInstrumentDetails() {
    return beneficiaryInstrumentDetails;
  }


  public void setBeneficiaryInstrumentDetails(CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails beneficiaryInstrumentDetails) {
    this.beneficiaryInstrumentDetails = beneficiaryInstrumentDetails;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateTransferResponseBeneficiaryDetails createTransferResponseBeneficiaryDetails = (CreateTransferResponseBeneficiaryDetails) o;
    return Objects.equals(this.beneficiaryId, createTransferResponseBeneficiaryDetails.beneficiaryId) &&
        Objects.equals(this.beneficiaryInstrumentDetails, createTransferResponseBeneficiaryDetails.beneficiaryInstrumentDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(beneficiaryId, beneficiaryInstrumentDetails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateTransferResponseBeneficiaryDetails {\n");
    sb.append("    beneficiaryId: ").append(toIndentedString(beneficiaryId)).append("\n");
    sb.append("    beneficiaryInstrumentDetails: ").append(toIndentedString(beneficiaryInstrumentDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("beneficiary_id");
    openapiFields.add("beneficiary_instrument_details");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CreateTransferResponseBeneficiaryDetails
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("beneficiary_id") != null && !jsonObj.get("beneficiary_id").isJsonNull()) && !jsonObj.get("beneficiary_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `beneficiary_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("beneficiary_id").toString()));
      }
      // validate the optional field `beneficiary_instrument_details`
      if (jsonObj.get("beneficiary_instrument_details") != null && !jsonObj.get("beneficiary_instrument_details").isJsonNull()) {
        CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails.validateJsonElement(jsonObj.get("beneficiary_instrument_details"));
      }
  }


  /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CreateTransferResponseBeneficiaryDetails
  */
  public static boolean validateJsonElementForOneOf(JsonElement jsonElement) throws IOException {

        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("beneficiary_id") != null && !jsonObj.get("beneficiary_id").isJsonNull()) && !jsonObj.get("beneficiary_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `beneficiary_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("beneficiary_id").toString()));
      }
      // validate the optional field `beneficiary_instrument_details`
      if (jsonObj.get("beneficiary_instrument_details") != null && !jsonObj.get("beneficiary_instrument_details").isJsonNull()) {
        CreateTransferResponseBeneficiaryDetailsBeneficiaryInstrumentDetails.validateJsonElement(jsonObj.get("beneficiary_instrument_details"));
        return true;
      }
      return false;
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateTransferResponseBeneficiaryDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateTransferResponseBeneficiaryDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateTransferResponseBeneficiaryDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateTransferResponseBeneficiaryDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateTransferResponseBeneficiaryDetails>() {
           @Override
           public void write(JsonWriter out, CreateTransferResponseBeneficiaryDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateTransferResponseBeneficiaryDetails read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CreateTransferResponseBeneficiaryDetails given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CreateTransferResponseBeneficiaryDetails
  * @throws IOException if the JSON string is invalid with respect to CreateTransferResponseBeneficiaryDetails
  */
  public static CreateTransferResponseBeneficiaryDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateTransferResponseBeneficiaryDetails.class);
  }

 /**
  * Convert an instance of CreateTransferResponseBeneficiaryDetails to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

